### PR TITLE
Update FR translation

### PR DESCRIPTION
**Pull request by Teoandro**

### CODE REVIEW

**Comment by KreAch3R** [comment]
Thank you @Teoandro for the translation. Unfortunately, it contains some build-error problems. Do you mind if I close this pull request and merge in [this](https://github.com/krexus/packages_apps_Settings/commit/64834bdd230b79ada4ffcb23f36a4c9d3451bebe) corrected commit instead? It keeps the authorship intact.

**Comment by Teoandro** [comment]
Thanks! No problem for merge your correction ;)

**Comment by KreAch3R** [comment]
Great @Teoandro! Thanks again for translating! I'll mention you in the upcoming update. :dancer: 

PR closed

**Comment by Teoandro** [comment]
Thanks to you @KreAch3R for making a super rom 👌

**Pull request closed without merging**
